ALTER TABLE BL_3NF.CE_ADDRESSES ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( ADDRESS_ID );
ALTER TABLE BL_3NF.CE_CHANNELS ADD CONSTRAINT CHANNELS_PK PRIMARY KEY ( CHANNEL_ID );
ALTER TABLE BL_3NF.CE_CITIES ADD CONSTRAINT CITIES_PK PRIMARY KEY ( CITY_ID );
ALTER TABLE BL_3NF.CE_COUNTRIES ADD CONSTRAINT COUNTRIES_PK PRIMARY KEY ( COUNTRY_ID );
ALTER TABLE BL_3NF.CE_CUSTOMERS_GEO ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY ( CUSTOMER_ID );
ALTER TABLE BL_3NF.CE_EMPLOYEE_POSITIONS ADD CONSTRAINT EMPLOYEE_POSITION_PK PRIMARY KEY ( EMPLOYEE_POSITION_ID );
ALTER TABLE BL_3NF.CE_EMPLOYEES ADD CONSTRAINT EMPLOYEES_PK PRIMARY KEY ( EMPLOYEE_ID );
ALTER TABLE BL_3NF.CE_PAYMENT_TYPES ADD CONSTRAINT PAYMENTS_TYPE_PK PRIMARY KEY ( PAYMENT_TYPE_ID );
ALTER TABLE BL_3NF.CE_PAYMENTS ADD CONSTRAINT FCT_PAYMENTS_PK PRIMARY KEY ( PAYMENT_ID );
ALTER TABLE BL_3NF.CE_PRODUCTS ADD CONSTRAINT PRODUCTS_PK PRIMARY KEY ( PRODUCT_ID );
ALTER TABLE BL_3NF.CE_STORES ADD CONSTRAINT STORES_PK PRIMARY KEY ( STORE_ID );


ALTER TABLE BL_3NF.CE_PAYMENTS ADD CONSTRAINT CE_PAYMENTS_CE_CUSTOMERS_GEO_FK FOREIGN KEY (CUSTOMER_ID ) REFERENCES BL_3NF.CE_CUSTOMERS_GEO ( CUSTOMER_ID );
ALTER TABLE BL_3NF.CE_CUSTOMERS_GEO ADD CONSTRAINT CE_CUSTOMERS_GEO_CE_ADDRESSES_FK FOREIGN KEY (ADDRESS_ID ) REFERENCES BL_3NF.CE_ADDRESSES ( ADDRESS_ID );
ALTER TABLE BL_3NF.CE_ADDRESSES ADD CONSTRAINT CE_ADDRESSES_CE_CITY_FK FOREIGN KEY (CITY_ID ) REFERENCES BL_3NF.CE_CITIES ( CITY_ID );
ALTER TABLE BL_3NF.CE_CITIES ADD CONSTRAINT CE_CITIES_CE_COUNTRY_FK FOREIGN KEY ( COUNTRY_ID ) REFERENCES BL_3NF.CE_COUNTRIES ( COUNTRY_ID );
ALTER TABLE BL_3NF.CE_PAYMENTS ADD CONSTRAINT CE_PAYMENTS_CE_CHANNELS_FK FOREIGN KEY (CHANNEL_ID ) REFERENCES BL_3NF.CE_CHANNELS ( CHANNEL_ID );
ALTER TABLE BL_3NF.CE_PAYMENTS ADD CONSTRAINT CE_PAYMENTS_CE_PRODUCTS_FK FOREIGN KEY (PRODUCT_ID ) REFERENCES BL_3NF.CE_PRODUCTS ( PRODUCT_ID );
ALTER TABLE BL_3NF.CE_PAYMENTS ADD CONSTRAINT CE_PAYMENT_TYPES_CE_PAYMENTS_FK FOREIGN KEY (PAYMENT_TYPE_ID ) REFERENCES BL_3NF.CE_PAYMENT_TYPES (PAYMENT_TYPE_ID );
ALTER TABLE BL_3NF.CE_PAYMENTS ADD CONSTRAINT CE_PAYMENTS_CE_STORES_FK FOREIGN KEY (STORE_ID ) REFERENCES BL_3NF.CE_STORES ( STORE_ID );
ALTER TABLE BL_3NF.CE_PAYMENTS ADD CONSTRAINT CE_PAYMENTS_CE_EMPLOYEES_FK FOREIGN KEY (EMPLOYEE_ID ) REFERENCES BL_3NF.CE_EMPLOYEES ( EMPLOYEE_ID );
ALTER TABLE BL_3NF.CE_EMPLOYEES ADD CONSTRAINT CE_EMPLOYEE_CE_EMPLOYEE_POSITION_FK FOREIGN KEY ( EMPLOYEE_POSITION_ID ) REFERENCES BL_3NF.CE_EMPLOYEE_POSITIONS ( EMPLOYEE_POSITION_ID );

