CREATE OR REPLACE PACKAGE PKG_FULL_LOAD_TO_3NF AS
    PROCEDURE PRC_LOAD_CE_COUNTRIES;
    PROCEDURE PRC_LOAD_CE_CITIES;
    PROCEDURE PRC_LOAD_CE_ADDRESSES;
    PROCEDURE PRC_LOAD_CE_STORES;
    PROCEDURE PRC_LOAD_CE_PRODUCTS;
    PROCEDURE PRC_LOAD_CE_EMPLOYEE_POSITIONS;
    PROCEDURE PRC_LOAD_CE_EMPLOYEES;
    PROCEDURE PRC_LOAD_CE_CHANNELS;
    PROCEDURE PRC_LOAD_CE_PAYMENT_TYPES;
    PROCEDURE PRC_LOAD_CE_CUSTOMERS_GEO;
    PROCEDURE PRC_LOAD_CE_PAYMENTS;
END PKG_FULL_LOAD_TO_3NF;


BEGIN 
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_COUNTRIES;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_CITIES;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_ADDRESSES;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_STORES;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_PRODUCTS;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_EMPLOYEE_POSITIONS;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_EMPLOYEES;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_CHANNELS;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_PAYMENT_TYPES;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_CUSTOMERS_GEO;
    PKG_FULL_LOAD_TO_3NF.PRC_LOAD_CE_PAYMENTS;
END;