-------------PACKAGE HEAD-------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_LOAD_FROM_EXT_TO_SA AS
    PROCEDURE PRC_LOAD_SRC_GET_QUICK_STORE; 
    PROCEDURE PRC_LOAD_SRC_EXPRESS_BAZAAR; 
END PKG_LOAD_FROM_EXT_TO_SA;


-------------CALL PROCEDURES----------------------------------------------------
BEGIN 
PKG_LOAD_FROM_EXT_TO_SA.PRC_LOAD_SRC_GET_QUICK_STORE;
PKG_LOAD_FROM_EXT_TO_SA.PRC_LOAD_SRC_EXPRESS_BAZAAR;
END;


