CREATE OR REPLACE PACKAGE PKG_FULL_LOAD_DIM_TABLES AS
    PROCEDURE PRC_LOAD_DIM_STORES;
    PROCEDURE PRC_LOAD_DIM_PRODUCTS;
    PROCEDURE PRC_LOAD_DIM_CHANNELS;
    PROCEDURE PRC_LOAD_DIM_PAYMENT_TYPE;
    PROCEDURE PRC_LOAD_DIM_DATES;
    PROCEDURE PRC_LOAD_DIM_CUSTOMERS_GEO;
    PROCEDURE PRC_LOAD_DIM_EMPLOYEES_SCD;
    PROCEDURE PRC_LOAD_FCT_PAYMENTS;
END PKG_FULL_LOAD_DIM_TABLES;


BEGIN
    PKG_FULL_LOAD_DIM_TABLES.PRC_LOAD_DIM_STORES;
    PKG_FULL_LOAD_DIM_TABLES.PRC_LOAD_DIM_PRODUCTS;
    PKG_FULL_LOAD_DIM_TABLES.PRC_LOAD_DIM_CHANNELS;
    PKG_FULL_LOAD_DIM_TABLES.PRC_LOAD_DIM_PAYMENT_TYPE;
    PKG_FULL_LOAD_DIM_TABLES.PRC_LOAD_DIM_DATES;
    PKG_FULL_LOAD_DIM_TABLES.PRC_LOAD_DIM_CUSTOMERS_GEO;
    PKG_FULL_LOAD_DIM_TABLES.PRC_LOAD_DIM_EMPLOYEES_SCD;
    PKG_FULL_LOAD_DIM_TABLES.PRC_LOAD_FCT_PAYMENTS;
END;