CREATE PUBLIC SYNONYM FCT_PAYMENTS_ID_SEQ FOR BL_DM.FCT_PAYMENTS_ID_SEQ;
CREATE PUBLIC SYNONYM DIM_STORES_ID_SEQ FOR BL_DM.DIM_STORES_ID_SEQ;
CREATE PUBLIC SYNONYM DIM_PRODUCTS_ID_SEQ FOR BL_DM.DIM_PRODUCTS_ID_SEQ;
CREATE PUBLIC SYNONYM DIM_PAYMENT_TYPES_ID_SEQ FOR BL_DM.DIM_PAYMENT_TYPES_ID_SEQ;
CREATE PUBLIC SYNONYM DIM_EMPLOYEE_SCD_ID_SEQ FOR BL_DM.DIM_EMPLOYEE_SCD_ID_SEQ;
CREATE PUBLIC SYNONYM DIM_CUSTOMER_GEO_ID_SEQ FOR BL_DM.DIM_CUSTOMER_GEO_ID_SEQ;
CREATE PUBLIC SYNONYM DIM_CHANNELS_ID_SEQ FOR BL_DM.DIM_CHANNELS_ID_SEQ;