CREATE OR REPLACE PUBLIC SYNONYM DIM_CHANNELS FOR BL_3NF.DIM_CHANNELS;
CREATE OR REPLACE PUBLIC SYNONYM DIM_CUSTOMERS_GEO FOR BL_3NF.DIM_CUSTOMERS_GEO;
CREATE OR REPLACE PUBLIC SYNONYM DIM_DATES FOR BL_3NF.DIM_DATES;
CREATE OR REPLACE PUBLIC SYNONYM DIM_EMPLOYEES_SCD FOR BL_3NF.DIM_EMPLOYEES_SCD;
CREATE OR REPLACE PUBLIC SYNONYM DIM_PAYMENT_TYPES FOR BL_3NF.DIM_PAYMENT_TYPES;
CREATE OR REPLACE PUBLIC SYNONYM DIM_STORES FOR BL_3NF.DIM_STORES;
CREATE OR REPLACE PUBLIC SYNONYM DIM_PRODUCTS FOR BL_3NF.DIM_PRODUCTS;
CREATE OR REPLACE PUBLIC SYNONYM FCT_PAYMENTS FOR BL_3NF.FCT_PAYMENTS;
