CREATE TABLE BL_DM.DIM_PRODUCTS (
            PRODUCT_SURR_ID NUMBER(38), 
            PRODUCT_SRC_ID  NUMBER(38),
            SOURCE_SYSTEM VARCHAR2(300),
            SOURCE_TABLE VARCHAR2(300),
            PRODUCT_NAME VARCHAR2(300),
            INSERT_DT DATE,
            UPDATE_DT DATE);
