CREATE TABLE BL_DM.DIM_CHANNELS ( CHANNEL_SURR_ID NUMBER(38), 
            CHANNEL_SRC_ID NUMBER(38),
            SOURCE_SYSTEM VARCHAR2(300),
            SOURCE_TABLE VARCHAR2(300),
            CHANNEL_NAME VARCHAR2(300),
            INSERT_DT DATE DEFAULT SYSDATE,
            UPDATE_DT DATE DEFAULT SYSDATE);
