CREATE TABLE BL_DM.DIM_EMPLOYEES_SCD (
            EMPLOYEE_SURR_ID    NUMBER(38), 
            EMPLOYEE_SRC_ID NUMBER(38),
            SOURCE_SYSTEM VARCHAR2(300),
            SOURCE_TABLE VARCHAR2(300),
            EMPLOYEE_LAST_NAME  VARCHAR2(300),
            EMPLOYEE_FIRST_NAME VARCHAR2(300),
            EMPLOYEE_POSITION   VARCHAR2(300),
            IS_CURRENT  VARCHAR2(300),
            START_DATE DATE,
            END_DATE  DATE,
            INSERT_DT DATE,
            UPDATE_DT  DATE);
