ALTER TABLE BL_DM.DIM_CHANNELS ADD CONSTRAINT DIM_CHANNELS_PK PRIMARY KEY ( CHANNEL_SURR_ID );
ALTER TABLE BL_DM.DIM_CUSTOMERS_GEO ADD CONSTRAINT DIM_CUSTOMERS_PK PRIMARY KEY ( CUSTOMER_SURR_ID );
ALTER TABLE BL_DM.DIM_DATES ADD CONSTRAINT DIM_DATES_PK PRIMARY KEY ( EVENT_DATE );
ALTER TABLE BL_DM.DIM_EMPLOYEES_SCD ADD CONSTRAINT DIM_EMPLOYEES_SCD_PK PRIMARY KEY ( EMPLOYEE_SURR_ID );
ALTER TABLE BL_DM.DIM_PAYMENT_TYPES ADD CONSTRAINT DIM_PAYMENT_TYPES_PK PRIMARY KEY ( PAYMENT_TYPE_SURR_ID );
ALTER TABLE BL_DM.DIM_PRODUCTS ADD CONSTRAINT DIM_PRODUCTS_PK PRIMARY KEY ( PRODUCT_SURR_ID );
ALTER TABLE BL_DM.DIM_STORES ADD CONSTRAINT DIM_STORES_PK PRIMARY KEY ( STORE_SURR_ID );


ALTER TABLE BL_DM.FCT_PAYMENTS ADD CONSTRAINT FCT_PAYMENTS_DIM_CHANNELS_FK FOREIGN KEY ( CHANNEL_SURR_ID ) REFERENCES BL_DM.DIM_CHANNELS ( CHANNEL_SURR_ID );
ALTER TABLE BL_DM.FCT_PAYMENTS ADD CONSTRAINT FCT_PAYM_DIM_CUST_GEO_FK FOREIGN KEY ( CUSTOMER_SURR_ID ) REFERENCES BL_DM.DIM_CUSTOMERS_GEO ( CUSTOMER_SURR_ID );
ALTER TABLE BL_DM.FCT_PAYMENTS ADD CONSTRAINT FCT_PAYMENTS_DIM_DATES_FK FOREIGN KEY ( EVENT_DATE ) REFERENCES BL_DM.DIM_DATES ( EVENT_DATE );
ALTER TABLE BL_DM.FCT_PAYMENTS ADD CONSTRAINT FCT_PAYM_DIM_EMPL_SCD_FK FOREIGN KEY ( EMPLOYEE_SURR_ID ) REFERENCES BL_DM.DIM_EMPLOYEES_SCD ( EMPLOYEE_SURR_ID );
ALTER TABLE BL_DM.FCT_PAYMENTS ADD CONSTRAINT FCT_PAYM_DIM_PAYM_TYPES_FK FOREIGN KEY ( PAYMENT_TYPE_SURR_ID ) REFERENCES BL_DM.DIM_PAYMENT_TYPES ( PAYMENT_TYPE_SURR_ID );
ALTER TABLE BL_DM.FCT_PAYMENTS ADD CONSTRAINT FCT_PAYM_DIM_PRODUCTS_FK FOREIGN KEY ( PRODUCT_SURR_ID ) REFERENCES BL_DM.DIM_PRODUCTS ( PRODUCT_SURR_ID );
ALTER TABLE BL_DM.FCT_PAYMENTS ADD CONSTRAINT FCT_PAYMENTS_DIM_STORES_FK FOREIGN KEY ( STORE_SURR_ID ) REFERENCES BL_DM.DIM_STORES ( STORE_SURR_ID );
