CREATE TABLE BL_3NF.CE_EMPLOYEES (
            EMPLOYEE_ID NUMBER(38) NOT NULL, 
            EMPLOYEE_SRC_ID VARCHAR2(300) NOT NULL,
            SOURCE_SYSTEM VARCHAR2(300) NOT NULL,
            SOURCE_TABLE VARCHAR2(300) NOT NULL,
            LAST_NAME VARCHAR2(300) NOT NULL,
            FIRST_NAME VARCHAR2(300) NOT NULL,
            STORE_ID NUMBER(38) NOT NULL,
            EMPLOYEE_POSITION_ID NUMBER(38) NOT NULL,
            IS_CURRENT VARCHAR(5) NOT NULL,
            START_DATE DATE NOT NULL,
            END_DATE DATE NOT NULL,
            UPDATE_DATE DATE NOT NULL,
            TA_INSERT_DATE DATE NOT NULL,
            TA_UPDATE_DATE DATE NOT NULL);
            
ALTER TABLE BL_3NF.CE_EMPLOYEES MODIFY TA_INSERT_DATE DEFAULT SYSDATE;
ALTER TABLE BL_3NF.CE_EMPLOYEES MODIFY TA_UPDATE_DATE DEFAULT SYSDATE;
ALTER TABLE BL_3NF.CE_EMPLOYEES MODIFY IS_CURRENT DEFAULT 'Y';
